### ISSUE TITLE
How is the project going?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [zeam-vm/hastega#1]
Hello!

I watched your conference a few months ago where you were announcing this project. In that presentation it was said Hastega would have it's first version before Summer 2019. 

We are in June 2019, so I was wondering how the project is going. Any major developments? Is it ready for use?

Best Regards, 
Just another fan.

**Comment by hisaway** [comment]
Thank you for your watching our Hastega!

Please see this: https://medium.com/@zacky1972/hastega-will-be-renamed-concludes-not-to-adopt-to-be-implemented-using-high-performance-erlang-d29666f93b69
